name: ci
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push base
        id: docker_build_base
        uses: docker/build-push-action@v2
        with:
          file: containers/base/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/zerotens/base:latest
      - name: Build and push base
        id: docker_build_vpn
        uses: docker/build-push-action@v2
        with:
          context: containers/openvpn/
          file: containers/openvpn/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/zerotens/openvpn:latest